import { useState } from "react";
import {
  LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid,
  BarChart, Bar, Legend,
} from "recharts";

const API_BASE = import.meta.env.VITE_API_BASE || "http://localhost:8000";
const EXAMPLES = ["AAPL", "TSLA", "NVDA", "MSFT"];

function App() {
  const [ticker, setTicker] = useState("");
  const [company, setCompany] = useState(null);
  const [prices, setPrices] = useState([]);
  const [financials, setFinancials] = useState([]);
  const [scores, setScores] = useState(null);
  const [period, setPeriod] = useState("1y");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [report, setReport] = useState("");
  const [reportLoading, setReportLoading] = useState(false);
  const [macro, setMacro] = useState([]);
  const [macroLoading, setMacroLoading] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);

  const fetchAll = async (tk, per) => {
    setLoading(true);
    setError("");
    setReport("");
    setMacro([]);
    setHasSearched(true);
    try {
      const [cRes, pRes, fRes, sRes] = await Promise.all([
        fetch(`${API_BASE}/company/${tk}`),
        fetch(`${API_BASE}/prices/${tk}?period=${per}`),
        fetch(`${API_BASE}/financials/${tk}`),
        fetch(`${API_BASE}/scores/${tk}`),
      ]);
      if (!cRes.ok || !pRes.ok) throw new Error("Request failed");
      const cData = await cRes.json();
      const pData = await pRes.json();
      const fData = await fRes.json();
      const sData = await sRes.json();
      if (!cData.name) throw new Error("Not found");
      setCompany(cData);
      setPrices(pData.prices || []);
      setFinancials(fData.financials || []);
      setScores(sData || null);
    } catch (err) {
      setError("Could not find that ticker. Try AAPL, TSLA, NVDA, or MSFT.");
      setCompany(null);
      setPrices([]);
      setFinancials([]);
      setScores(null);
    } finally {
      setLoading(false);
    }
  };

  const runSearch = (value) => {
    const tk = (value || ticker).trim().toUpperCase();
    if (!tk) return;
    setTicker(tk);
    document.getElementById("analyze")?.scrollIntoView({ behavior: "smooth" });
    fetchAll(tk, period);
  };

  const handlePeriodChange = (newPeriod) => {
    setPeriod(newPeriod);
    if (company) fetchAll(company.ticker, newPeriod);
  };

  const handleGenerateReport = async () => {
    if (!company) return;
    setReportLoading(true);
    setReport("");
    try {
      const res = await fetch(`${API_BASE}/report/${company.ticker}`);
      if (!res.ok) throw new Error("Report failed");
      const data = await res.json();
      setReport(data.report || "");
    } catch (err) {
      setReport("Failed to generate report. Please try again.");
    } finally {
      setReportLoading(false);
    }
  };

  const handleMacro = async () => {
    if (!company) return;
    setMacroLoading(true);
    setMacro([]);
    try {
      const res = await fetch(`${API_BASE}/macro/${company.ticker}`);
      if (!res.ok) throw new Error("Macro failed");
      const data = await res.json();
      setMacro(data.macro_factors || []);
    } catch (err) {
      setMacro([]);
    } finally {
      setMacroLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") runSearch();
  };

  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });

  const formatMarketCap = (n) => {
    if (!n) return "N/A";
    if (n >= 1e12) return `$${(n / 1e12).toFixed(2)}T`;
    if (n >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
    return `$${n.toLocaleString()}`;
  };

  const periods = ["1mo", "6mo", "1y", "5y"];
  const impactColor = (impact) =>
    impact === "Positive" ? "#34d399" : impact === "Negative" ? "#f87171" : "#fbbf24";

  const features = [
    { icon: "📊", title: "Financial Visualization", desc: "Interactive charts of revenue, margins, and profit trends from real market data." },
    { icon: "🤖", title: "AI Research Reports", desc: "Structured investment reports generated by AI, grounded in real financial data." },
    { icon: "⚠️", title: "Risk & Quality Scores", desc: "Rule-based scoring across growth, profitability, and valuation risk." },
    { icon: "🌐", title: "Macro Analysis", desc: "AI connects macroeconomic factors to each company's specific business." },
  ];

  const steps = [
    { n: "1", title: "Enter a ticker", desc: "Type a US stock symbol or pick an example below." },
    { n: "2", title: "Explore the data", desc: "See company info, price trends, financials, and risk scores." },
    { n: "3", title: "Generate AI insights", desc: "Get a macro analysis and a full AI research report on demand." },
  ];

  return (
    <div style={styles.page}>
      {/* inline CSS for hover/animation that inline styles can't do */}
      <style>{`
        .hoverable { transition: all 0.18s ease; }
        .hoverable:hover { transform: translateY(-2px); }
        .feat:hover { border-color:#38bdf8 !important; box-shadow:0 6px 24px rgba(56,189,248,0.10); }
        .exampleBtn:hover { background:#0c2740 !important; border-color:#38bdf8 !important; color:#38bdf8 !important; }
        .cta:hover { filter:brightness(1.1); transform:translateY(-1px); }
        .navlink:hover { color:#e2e8f0 !important; }
        .card-anim { animation: fadeUp 0.4s ease both; }
        @keyframes fadeUp { from{opacity:0; transform:translateY(12px);} to{opacity:1; transform:translateY(0);} }
        .dot { display:inline-block; width:8px; height:8px; border-radius:50%; background:#38bdf8; margin-right:8px; animation: pulse 1s infinite; }
        @keyframes pulse { 0%,100%{opacity:0.3;} 50%{opacity:1;} }
        input:focus { border-color:#38bdf8 !important; }
      `}</style>

      {/* NAVBAR */}
      <nav style={styles.nav}>
        <div style={styles.navInner}>
          <div style={styles.logo}>Kin<span style={styles.logoAccent}>stars</span></div>
          <div style={styles.navLinks}>
            <span className="navlink" style={styles.navLink} onClick={() => scrollTo("features")}>How it works</span>
            <span className="navlink" style={styles.navLink} onClick={() => scrollTo("analyze")}>Analyze</span>
            <span className="cta" style={styles.navCta} onClick={() => scrollTo("analyze")}>Try it free</span>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section style={styles.hero}>
        <div style={styles.heroGlow} />
        <div style={styles.heroContent}>
          <div style={styles.heroBadge}>AI · Finance · Data</div>
          <h1 style={styles.heroTitle}>
            AI-Powered <span style={styles.heroTitleAccent}>Financial Research</span>
          </h1>
          <p style={styles.heroSub}>
            Analyze any US stock with real market data, financial trends, risk scoring,
            macro insights, and AI-generated research reports — all in one place.
          </p>
          <div style={styles.heroSearchRow}>
            <input
              style={styles.heroInput}
              placeholder="Enter a ticker (e.g. AAPL)"
              value={ticker}
              onChange={(e) => setTicker(e.target.value)}
              onKeyDown={handleKeyDown}
            />
            <button className="cta" style={styles.heroButton} onClick={() => runSearch()}>Analyze →</button>
          </div>
          <div style={styles.exampleRow}>
            <span style={styles.exampleLabel}>Try:</span>
            {EXAMPLES.map((ex) => (
              <span key={ex} className="exampleBtn" style={styles.exampleBtn} onClick={() => runSearch(ex)}>{ex}</span>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="features" style={styles.section}>
        <div style={styles.sectionInner}>
          <h2 style={styles.sectionTitle}>How it works</h2>
          <p style={styles.sectionSub}>Three simple steps from ticker to full research report.</p>
          <div style={styles.stepGrid}>
            {steps.map((s) => (
              <div key={s.n} style={styles.stepCard}>
                <div style={styles.stepNum}>{s.n}</div>
                <div style={styles.featureTitle}>{s.title}</div>
                <div style={styles.featureDesc}>{s.desc}</div>
              </div>
            ))}
          </div>

          <h2 style={{ ...styles.sectionTitle, marginTop: "70px" }}>What you get</h2>
          <p style={styles.sectionSub}>A complete AI research workflow in one dashboard.</p>
          <div style={styles.featureGrid}>
            {features.map((f, i) => (
              <div key={i} className="feat hoverable" style={styles.featureCard}>
                <div style={styles.featureIcon}>{f.icon}</div>
                <div style={styles.featureTitle}>{f.title}</div>
                <div style={styles.featureDesc}>{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ANALYZE TOOL */}
      <section id="analyze" style={styles.section}>
        <div style={styles.toolInner}>
          <h2 style={styles.sectionTitle}>Live Analysis</h2>
          <p style={styles.sectionSub}>Enter a ticker to generate a full research dashboard.</p>

          {/* Empty-state guide before any search */}
          {!hasSearched && !loading && (
            <div style={styles.guideBox}>
              <div style={styles.guideTitle}>👋 Start by choosing a company</div>
              <p style={styles.guideText}>Pick one to instantly generate its full analysis:</p>
              <div style={styles.guideBtnRow}>
                {EXAMPLES.map((ex) => (
                  <span key={ex} className="exampleBtn hoverable" style={styles.guideBtn} onClick={() => runSearch(ex)}>{ex}</span>
                ))}
              </div>
            </div>
          )}

          {loading && (
            <p style={styles.info}><span className="dot" />Fetching data and building your dashboard...</p>
          )}
          {error && <p style={styles.error}>{error}</p>}

          {company && (
            <>
              <div className="card-anim" style={styles.card}>
                <div style={styles.overviewHeader}>
                  <div>
                    <h2 style={styles.cardName}>{company.name}</h2>
                    <span style={styles.cardTicker}>{company.ticker}</span>
                  </div>
                  <div style={styles.priceBox}>
                    <div style={styles.priceLabel}>Current Price</div>
                    <div style={styles.priceValue}>{company.current_price ? `$${company.current_price}` : "N/A"}</div>
                  </div>
                </div>
                <div style={styles.grid}>
                  <Metric label="Sector" value={company.sector || "N/A"} />
                  <Metric label="Industry" value={company.industry || "N/A"} />
                  <Metric label="Market Cap" value={formatMarketCap(company.market_cap)} />
                  <Metric label="P/E (Trailing)" value={company.pe_trailing ? company.pe_trailing.toFixed(2) : "N/A"} />
                  <Metric label="P/E (Forward)" value={company.pe_forward ? company.pe_forward.toFixed(2) : "N/A"} />
                  <Metric label="Currency" value={company.currency || "N/A"} />
                </div>
                {company.summary && <p style={styles.summary}>{company.summary}</p>}
                <div style={styles.scrollHint}>↓ Scroll down for charts, risk scores, and AI analysis</div>
              </div>

              {prices.length > 0 && (
                <div className="card-anim" style={styles.card}>
                  <div style={styles.chartHeader}>
                    <h3 style={styles.chartTitle}>Price History</h3>
                    <div style={styles.periodRow}>
                      {periods.map((p) => (
                        <button key={p} className="hoverable"
                          style={{ ...styles.periodBtn, ...(period === p ? styles.periodBtnActive : {}) }}
                          onClick={() => handlePeriodChange(p)}>{p}</button>
                      ))}
                    </div>
                  </div>
                  <ResponsiveContainer width="100%" height={300}>
                    <LineChart data={prices}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                      <XAxis dataKey="date" stroke="#64748b" tick={{ fontSize: 11 }} minTickGap={40} />
                      <YAxis stroke="#64748b" tick={{ fontSize: 11 }} domain={["auto", "auto"]} />
                      <Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: "8px", color: "#e2e8f0" }} />
                      <Line type="monotone" dataKey="close" stroke="#38bdf8" strokeWidth={2} dot={false} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              )}

              {financials.length > 0 && (
                <div className="card-anim" style={styles.card}>
                  <h3 style={styles.chartTitle}>Financial Performance (USD Billions)</h3>
                  <ResponsiveContainer width="100%" height={320}>
                    <BarChart data={financials} margin={{ top: 20, right: 10, left: 0, bottom: 0 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                      <XAxis dataKey="year" stroke="#64748b" tick={{ fontSize: 12 }} />
                      <YAxis stroke="#64748b" tick={{ fontSize: 11 }} />
                      <Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: "8px", color: "#e2e8f0" }} />
                      <Legend wrapperStyle={{ fontSize: "12px" }} />
                      <Bar dataKey="revenue" name="Revenue" fill="#38bdf8" radius={[3, 3, 0, 0]} />
                      <Bar dataKey="gross_profit" name="Gross Profit" fill="#34d399" radius={[3, 3, 0, 0]} />
                      <Bar dataKey="operating_income" name="Operating Income" fill="#fbbf24" radius={[3, 3, 0, 0]} />
                      <Bar dataKey="net_income" name="Net Income" fill="#a78bfa" radius={[3, 3, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              )}

              {scores && (
                <div className="card-anim" style={styles.card}>
                  <h3 style={styles.chartTitle}>Risk & Quality Scores</h3>
                  <div style={styles.scoreGrid}>
                    <ScoreCard label="Growth" value={scores.growth_score}
                      detail={scores.revenue_growth_pct != null ? `Rev +${scores.revenue_growth_pct}%` : ""} good="High" />
                    <ScoreCard label="Profitability" value={scores.profitability_score}
                      detail={scores.net_margin_pct != null ? `Margin ${scores.net_margin_pct}%` : ""} good="High" />
                    <ScoreCard label="Valuation Risk" value={scores.valuation_risk}
                      detail={scores.pe != null ? `P/E ${scores.pe}` : ""} good="Low" />
                    <ScoreCard label="Overall Risk" value={scores.overall_risk} detail="" good="Low" />
                  </div>
                </div>
              )}

              <div className="card-anim" style={styles.card}>
                <div style={styles.chartHeader}>
                  <div>
                    <h3 style={styles.chartTitle}>Macroeconomic Impact</h3>
                    <p style={styles.hintText}>Click to let AI analyze how macro factors affect {company.ticker}.</p>
                  </div>
                  <button className="cta" style={styles.actionBtn} onClick={handleMacro} disabled={macroLoading}>
                    {macroLoading ? "Analyzing..." : "Analyze Macro"}
                  </button>
                </div>
                {macroLoading && <p style={styles.info}><span className="dot" />AI is analyzing macro factors...</p>}
                {macro.length > 0 && !macroLoading && (
                  <div>
                    {macro.map((f, i) => (
                      <div key={i} style={styles.macroItem}>
                        <div style={styles.macroHeader}>
                          <span style={styles.macroFactor}>{f.factor}</span>
                          <span style={{ ...styles.macroBadge, background: impactColor(f.impact) }}>{f.impact}</span>
                        </div>
                        <p style={styles.macroExp}>{f.explanation}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div className="card-anim" style={styles.card}>
                <div style={styles.chartHeader}>
                  <div>
                    <h3 style={styles.chartTitle}>AI Investment Research Report</h3>
                    <p style={styles.hintText}>Generate a full report from company overview to investment conclusion.</p>
                  </div>
                  <button className="cta" style={styles.actionBtn} onClick={handleGenerateReport} disabled={reportLoading}>
                    {reportLoading ? "Generating..." : "Generate Report"}
                  </button>
                </div>
                {reportLoading && <p style={styles.info}><span className="dot" />AI is writing the report... this may take a few seconds.</p>}
                {report && !reportLoading && (
                  <div style={styles.reportText}>
                    {report.split("\n").map((line, i) => (<p key={i} style={styles.reportLine}>{line}</p>))}
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      </section>

      {/* FOOTER */}
      <footer style={styles.footer}>
        <div style={styles.footerInner}>
          <div style={styles.footerLogo}>Kin<span style={styles.logoAccent}>stars</span></div>
          <p style={styles.footerText}>AI Financial Research Assistant · Built with React, FastAPI, yfinance & Gemini</p>
          <p style={styles.footerCopy}>© 2026 Kinstars. For educational and research purposes only.</p>
        </div>
      </footer>
    </div>
  );
}

function Metric({ label, value }) {
  return (
    <div style={styles.metric}>
      <div style={styles.metricLabel}>{label}</div>
      <div style={styles.metricValue}>{value}</div>
    </div>
  );
}

function ScoreCard({ label, value, detail, good }) {
  let color = "#64748b";
  if (value === good) color = "#34d399";
  else if (value === "Medium") color = "#fbbf24";
  else if (value !== "N/A") color = "#f87171";
  return (
    <div style={{ ...styles.scoreCard, borderColor: color }}>
      <div style={styles.scoreLabel}>{label}</div>
      <div style={{ ...styles.scoreValue, color }}>{value}</div>
      {detail && <div style={styles.scoreDetail}>{detail}</div>}
    </div>
  );
}

const mono = "'SF Mono', 'Roboto Mono', Menlo, monospace";

const styles = {
  page: { minHeight: "100vh", background: "#080d1a", color: "#e2e8f0", fontFamily: "system-ui, -apple-system, sans-serif" },
  nav: { position: "sticky", top: 0, zIndex: 50, background: "rgba(8,13,26,0.8)", backdropFilter: "blur(12px)", borderBottom: "1px solid #1e293b" },
  navInner: { maxWidth: "1080px", margin: "0 auto", padding: "16px 24px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  logo: { fontSize: "22px", fontWeight: "800", letterSpacing: "-0.5px" },
  logoAccent: { color: "#38bdf8" },
  navLinks: { display: "flex", gap: "28px", alignItems: "center" },
  navLink: { fontSize: "14px", color: "#94a3b8", cursor: "pointer" },
  navCta: { fontSize: "14px", fontWeight: "600", color: "#fff", background: "#0284c7", padding: "8px 18px", borderRadius: "8px", cursor: "pointer" },
  hero: { position: "relative", overflow: "hidden", padding: "100px 24px 90px", textAlign: "center", borderBottom: "1px solid #1e293b" },
  heroGlow: { position: "absolute", top: "-200px", left: "50%", transform: "translateX(-50%)", width: "700px", height: "500px", background: "radial-gradient(circle, rgba(56,189,248,0.18), transparent 70%)", pointerEvents: "none" },
  heroContent: { position: "relative", maxWidth: "760px", margin: "0 auto" },
  heroBadge: { display: "inline-block", fontSize: "12px", letterSpacing: "1.5px", color: "#38bdf8", border: "1px solid #1e3a5f", borderRadius: "20px", padding: "6px 16px", marginBottom: "28px", textTransform: "uppercase" },
  heroTitle: { fontSize: "54px", fontWeight: "800", lineHeight: "1.1", margin: 0, letterSpacing: "-1.5px" },
  heroTitleAccent: { background: "linear-gradient(90deg,#38bdf8,#818cf8)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" },
  heroSub: { fontSize: "18px", color: "#94a3b8", lineHeight: "1.6", marginTop: "24px", maxWidth: "600px", marginLeft: "auto", marginRight: "auto" },
  heroSearchRow: { display: "flex", gap: "10px", marginTop: "40px", maxWidth: "560px", marginLeft: "auto", marginRight: "auto" },
  heroInput: { flex: 1, padding: "16px 20px", fontSize: "16px", borderRadius: "12px", border: "1px solid #334155", background: "#0f172a", color: "#e2e8f0", outline: "none" },
  heroButton: { padding: "16px 28px", fontSize: "16px", borderRadius: "12px", border: "none", background: "linear-gradient(90deg,#0ea5e9,#6366f1)", color: "white", cursor: "pointer", fontWeight: "700", whiteSpace: "nowrap" },
  exampleRow: { display: "flex", gap: "10px", justifyContent: "center", alignItems: "center", marginTop: "20px", flexWrap: "wrap" },
  exampleLabel: { fontSize: "13px", color: "#64748b" },
  exampleBtn: { fontSize: "13px", color: "#94a3b8", border: "1px solid #334155", borderRadius: "8px", padding: "6px 14px", cursor: "pointer", fontFamily: mono },
  section: { padding: "70px 24px" },
  sectionInner: { maxWidth: "1080px", margin: "0 auto", textAlign: "center" },
  toolInner: { maxWidth: "860px", margin: "0 auto" },
  sectionTitle: { fontSize: "34px", fontWeight: "800", margin: 0, letterSpacing: "-0.8px" },
  sectionSub: { fontSize: "16px", color: "#94a3b8", marginTop: "12px", marginBottom: "44px" },
  stepGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))", gap: "20px" },
  stepCard: { background: "#0f172a", border: "1px solid #1e293b", borderRadius: "16px", padding: "28px 22px", textAlign: "left" },
  stepNum: { width: "38px", height: "38px", borderRadius: "10px", background: "linear-gradient(135deg,#0ea5e9,#6366f1)", color: "#fff", fontSize: "18px", fontWeight: "800", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "16px" },
  featureGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "20px" },
  featureCard: { background: "#0f172a", border: "1px solid #1e293b", borderRadius: "16px", padding: "28px 22px", textAlign: "left", cursor: "default" },
  featureIcon: { fontSize: "28px", marginBottom: "16px" },
  featureTitle: { fontSize: "17px", fontWeight: "700", marginBottom: "10px" },
  featureDesc: { fontSize: "14px", color: "#94a3b8", lineHeight: "1.6" },
  guideBox: { background: "#0f172a", border: "1px dashed #334155", borderRadius: "16px", padding: "40px 24px", textAlign: "center", marginTop: "10px" },
  guideTitle: { fontSize: "20px", fontWeight: "700" },
  guideText: { fontSize: "14px", color: "#94a3b8", marginTop: "10px" },
  guideBtnRow: { display: "flex", gap: "12px", justifyContent: "center", marginTop: "20px", flexWrap: "wrap" },
  guideBtn: { fontSize: "15px", fontWeight: "600", color: "#38bdf8", border: "1px solid #1e3a5f", background: "#0c2740", borderRadius: "10px", padding: "10px 22px", cursor: "pointer", fontFamily: mono },
  info: { color: "#94a3b8", marginTop: "20px", textAlign: "center" },
  error: { color: "#f87171", marginTop: "20px", textAlign: "center" },
  card: { marginTop: "24px", padding: "26px", borderRadius: "16px", background: "#0f172a", border: "1px solid #1e293b", textAlign: "left" },
  overviewHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "20px" },
  cardName: { margin: 0, fontSize: "24px", fontWeight: "700" },
  cardTicker: { display: "inline-block", fontSize: "13px", color: "#38bdf8", background: "#0c2740", padding: "3px 10px", borderRadius: "6px", marginTop: "8px", fontFamily: mono },
  priceBox: { textAlign: "right" },
  priceLabel: { fontSize: "12px", color: "#64748b" },
  priceValue: { fontSize: "28px", fontWeight: "800", fontFamily: mono },
  grid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "12px", marginTop: "8px" },
  metric: { background: "#080d1a", padding: "14px", borderRadius: "10px", border: "1px solid #1e293b" },
  metricLabel: { fontSize: "12px", color: "#64748b" },
  metricValue: { fontSize: "17px", fontWeight: "600", marginTop: "6px", fontFamily: mono },
  summary: { marginTop: "20px", fontSize: "14px", lineHeight: "1.7", color: "#94a3b8" },
  scrollHint: { marginTop: "20px", fontSize: "13px", color: "#38bdf8", textAlign: "center" },
  chartHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "16px" },
  chartTitle: { margin: 0, fontSize: "18px", fontWeight: "700", marginBottom: "8px" },
  hintText: { fontSize: "13px", color: "#64748b", margin: 0 },
  periodRow: { display: "flex", gap: "6px" },
  periodBtn: { padding: "5px 13px", fontSize: "13px", borderRadius: "7px", border: "1px solid #1e293b", background: "#080d1a", color: "#94a3b8", cursor: "pointer", fontFamily: mono },
  periodBtnActive: { background: "#0284c7", color: "white", border: "1px solid #0284c7" },
  actionBtn: { padding: "9px 20px", fontSize: "14px", borderRadius: "9px", border: "none", background: "linear-gradient(90deg,#0ea5e9,#6366f1)", color: "white", cursor: "pointer", fontWeight: "600", whiteSpace: "nowrap" },
  reportText: { marginTop: "10px" },
  reportLine: { fontSize: "14px", lineHeight: "1.7", color: "#cbd5e1", margin: "6px 0" },
  scoreGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "12px" },
  scoreCard: { background: "#080d1a", padding: "18px", borderRadius: "12px", border: "2px solid #1e293b", textAlign: "center" },
  scoreLabel: { fontSize: "12px", color: "#64748b" },
  scoreValue: { fontSize: "20px", fontWeight: "700", marginTop: "6px" },
  scoreDetail: { fontSize: "11px", color: "#64748b", marginTop: "5px", fontFamily: mono },
  macroItem: { background: "#080d1a", padding: "16px", borderRadius: "12px", marginBottom: "10px", border: "1px solid #1e293b" },
  macroHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  macroFactor: { fontSize: "15px", fontWeight: "600" },
  macroBadge: { fontSize: "11px", fontWeight: "700", color: "#080d1a", padding: "3px 11px", borderRadius: "12px" },
  macroExp: { fontSize: "13px", lineHeight: "1.6", color: "#94a3b8", marginTop: "8px", marginBottom: 0 },
  footer: { borderTop: "1px solid #1e293b", padding: "50px 24px", textAlign: "center" },
  footerInner: { maxWidth: "1080px", margin: "0 auto" },
  footerLogo: { fontSize: "20px", fontWeight: "800", marginBottom: "12px" },
  footerText: { fontSize: "14px", color: "#94a3b8", margin: "6px 0" },
  footerCopy: { fontSize: "12px", color: "#475569", marginTop: "16px" },
};

export default App;